### ISSUE TITLE
How to configure ports and usage of ipv4 addressing only

### ISSUE THREAD

**Issue by bwssytems** [SignalK/signalk-java#16]
How do you specify ports being used and have only ipv4 addressing?

Also, skip using https and use just http.

**Comment by rob42** [comment]
I havent checked but I think it defaults to IPv4? Its hard-coded for now, but could be made configurable if thats useful?

You can configure ports and http/https in the configuration screen. They will change on restart. It defaults to https, port 8443, so that no root priveleges are needed for the server.

**Comment by rob42** [comment]
Just checked defaults to prefer IPV4:
```
Properties props = System.getProperties();
		props.setProperty("java.net.preferIPv4Stack", "true");
```
In `nz.co.fortytwo.signalk.artemis.server.ArtemisServer`

**Comment by bwssytems** [comment]
Unfortunately, if I remember about java and ipv4, that does not work from in the code. You actually have to pass that on the command line. Had that same issue with my ha-bridge software for home automation https://github.com/bwssytems/ha-bridge#-djavanetpreferipv4stacktrue. Currently on my Linux mint 19 (Ubuntu Bionic Beaver base) it opens as the global ipv4/6 type.

Anyways, got out of the https and using port 8080 and all is much better. And I see that that port change is really for the RestAPI. Thanks for helping out!
